### ISSUE TITLE
Download font links broken

### ISSUE THREAD

**Issue by raphaelbastide** [mother-type/mother-type.de#2]
The font’s download links to github are 404.

**Comment by printerscanner** [comment]
Ah good catch 😳 . Looks like some files were named wrong.

**Comment by raphaelbastide** [comment]
By the way we added your foundry to https://velvetyne.fr/velvetyne-libre-friends/

**Comment by printerscanner** [comment]
Wow, that's seriously incredible. I better get to work on it then 🙃.
